apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: airensurzyn/llp-courses
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://courses-mongo-srv:27017/courses'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: gakko
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: courses-srv
spec:
  selector:
    app: courses
  ports:
    - name: courses
      protocol: TCP
      port: 3000
      targetPort: 3000
