apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: airensurzyn/llp-course
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/courses'
---
apiVersion: v1
kind: Service
metadata:
  name: course-srv
spec:
  selector:
    app: course
  ports:
    - name: course
      protocol: TCP
      port: 3000
      targetPort: 3000
